version=0.2.13-SNAPSHOT
lionwebJavaVersion=2024.1-core:1.3.2
mpsVersionSuffix=2025.1
mpsVersion=2025.1.2
jbrVersion=21.0.6-b895.109
mpsExtensionsVersion=2025.1.+
comSpecificlanguagesMpsVersion=2.0.1
comSpecificlanguagesJbrToolchainVersion=1.0.2
netResearchgateReleaseVersion=3.1.0
comVanniktechMavenPublishVersion=0.36.0
mpsGradleCommonVersion=1.30.+
mpsGradleLauncherVersion=2.8.+
apacheCliVersion=1.6.0
usedGradleVersion=9.2.1