version=0.2.13-SNAPSHOT
lionwebRelease=2023.1
lionwebJavaVersion=2024.1-core:1.3.2
mpsVersionSuffix=2025.1
mpsVersion=2025.1
jbrVersion=21.0.6-b895.109
mpsExtensionsVersion=2025.1.3288.fa63e64
comSpecificlanguagesMpsVersion=2.0.0-pre2
comSpecificlanguagesJbrToolchainVersion=1.0.2
netResearchgateReleaseVersion=3.0.2
comVanniktechMavenPublishVersion=0.31.0
apacheCliVersion=1.6.0