version=0.2.12-SNAPSHOT
lionwebRelease=2023.1
lionwebJavaVersion=2024.1-core:0.3.4
mpsVersionSuffix=2021.2
mpsVersion=2021.2.6
jbrVersion=11_0_14_1-b1751.46
mpsExtensionsVersion=2021.2.2631.1360a64
comSpecificlanguagesMpsVersion=2.0.0-pre2
comSpecificlanguagesJbrToolchainVersion=1.0.2
netResearchgateReleaseVersion=3.0.2
comVanniktechMavenPublishVersion=0.31.0
apacheCliVersion=1.6.0