@startuml
hide empty members

' qualified name: "io.lionweb.derived.validation"


interface IFinding {
  severity: Severity?
  message: String?
}

interface INodeFinding extends IFinding
enum Severity {
  info
  warning
  error
}



' relations:


INodeFinding "*" --> "*" Node: appliesTo


@enduml
