= LionWeb MPS Command Line Exporter
:icons: font

== Usage

Gradle requires some workarounds to pass arguments, so we have to wrap our command-line arguments in `-Pargs`:

[source,shell]
----
./gradlew runCommandLineTool -Pargs="-help"
----

This would print

----
> Task :runCommandLineTool
usage: lionweb-export-language [<config-file>] <output-file>
 -help                   print this message
 -ic,--instanceConfigs   executes all 'Export Instance to JSON'
                         configurations
 -l,--language <arg>     convert language with key <args>, or
                         <key>@<version>
 -lc,--languageConfigs   executes all 'Export Language to JSON'
                         configurations
 -s,--scope <arg>        set export scope: listed, indirect,
                         fineGrainedClosure
----

config-file::
Optional; if provided, it must be a json file with two properties:

* `scope` takes the same values as `-s` parameter. If both are present, the parameter prevails.
* `languages` contains a list of language keys to export.

output-file::
The file the converted languages should be written to.
All languages will be written to the same file.

instanceConfigs::
Executes all link:../../docs/reference/converter-lang.adoc#instance-json-export[`ExportInstanceToJson`] configurations.

language::
Supplies the key of a language to export.
Can be used multiple times; we accumulate all keys from _config-file_ and _language_ parameters.
+
We export languages based on their _structure aspect_ representation.
+
[NOTE]
--
We're always using the language's link:../../docs/reference/structure-extensions.adoc#custom-keys[key].
 We're _not_ using the language's fully qualified name, module name, uuid, or anything else.
--

scope::
Defines the export link:../../docs/reference/converter-lang.adoc#language-json[scope as explained for converter languages].

languageConfigs::
Executes all link:../../docs/reference/converter-lang.adoc#language-json-export[`ExportSLanguageToJson`]
and link:../../docs/reference/converter-lang.adoc#mps-language-json-export[`ExportMpsLanguageStructureToJson`]
configurations.

[NOTE]
--
We moved some command-line arguments to the gradle script. This includes:

* _project_dir_: Previously the first positional command-line parameter. Replace with proper
https://github.com/mbeddr/mps-gradle-plugin/blob/v1.x/docs/tasks/MpsExecute.md[`projectLocation`]
value.
* `-m` or `--macro`: Previously command-line parameters. Macros now must be https://github.com/specificlanguages/mps-gradle-plugin/tree/master/subprojects/mps-gradle-plugin#customizing-conventions[added] to the gradle script:
+
[source,gradle]
----
mpsDefaults.pathVariables.put("lionweb-mps.home", projectDir.resolve("build/dependencies/io.lionweb.mps"))
----
--

[NOTE]
--
We assume that you downloaded all dependencies for your to-be-exported languages.
This is typically done by running the Gradle `setup` task, as follows:

[source,shell]
----
./gradlew setup
----
--

=== Examples

==== Minimal usage example without config file

[source,shell]
----
./gradlew runCommandLineTool -Pargs="exported.lw-lang.json -lMyHappyLittleMulti-Reference_Language -s=listed"
----

* `exported.lw-lang.json` sets the output file
* `-lMyHappyLittleMulti-Reference_Language` asks to export the language with key `MyHappyLittleMulti-Reference_Language`
* `-s=listed` sets the export scope to _listed_

==== Example with config file

[source,shell]
----
./gradlew runCommandLineTool -Pargs="config-file.json exported.lw-lang.json"
----

* `config-file.json` specifies the file that provides scope and language keys.
 Useful to keep the language keys under version control.
* `exported.lw-lang.json` sets the output file

Contents of `config-file.json`:

[source,json]
----
{
  "scope": "listed",
  "languages": [
    {
      "key": "NTM3ZjljYjAtMGYyNS0zYzc2LThiODYtMzA4ZjQ1MDEwMTAw",
      "version": "0"
    },
    {
      "key": "MyHappyLittleMulti-Reference_Language",
      "version": "1"
    }
  ]
}
----

==== Example to export all instance and language configs in the project

[source,shell]
----
./gradlew runCommandLineTool -Pargs="-ic -lc"
----

==== Test exports

The directories `test-project/` and `test-project-externalLib` contain MPS projects that can be used to test the command-line exporter.

Within `test-project/`, run

[source,shell]
----
source scripts/export-library.sh
source scripts/export-multiple.sh
source scripts/export-foo.sh
----

(or a similar incantation suitable for your OS and shell) to export three example languages, and compare the exports to the reference exports in `expected/`.
The languages' exports end up in the `actual/` directory.
The `FooLanguage` language resides within the project, but the `library` and `multi` language are bundled.
The `export-multiple.sh` script also demonstrates the use of a JSON configuration file — in this case link:../../test-project/export-multiple.config.json[`export-multiple.config.json`].

Within `test-project-externalLib`, run

[source,shell]
----
source scripts/export-DependsOnMpsExtensions.sh
source scripts/export-foo.sh
----

(or a similar incantation suitable for your OS and shell) to export two example languages in the same way as in the `test-project`.
The `FooLanguage` language resides within the `test-project/` MPS project, and the `DependsOnMpsExtensions` depends on the `de.slisson.mps.richtext` language from the MPS extensions.

== Setup

We assume the MPS project that contains your to-be-exported languages is built with Gradle using https://github.com/specificlanguages/mps-gradle-plugin/tree/master/subprojects/mps-gradle-plugin[SpecificLanguages mps-gradle-plugin].

NOTE: This example is condensed to one file.
In a production environment, consider https://docs.gradle.org/current/userguide/version_catalogs.html[externalizing versions] (https://github.com/LionWeb-io/lionweb-mps/blob/mps2025.1/test-project-externalLib/build.gradle.kts[example]).

Create or adjust the following contents of `build.gradle.kts` (Kotlin dialect):

[source,gradle]
----
// based on https://github.com/specificlanguages/mps-gradle-plugin-sample

import com.specificlanguages.mps.MainBuild
import de.itemis.mps.gradle.tasks.MpsExecute
import org.apache.commons.exec.CommandLine

buildscript {
    dependencies {
        classpath("org.apache.commons:commons-exec:1.6.+")                         // <1>
    }
}

plugins {
    id("com.specificlanguages.mps") version "2.0.1"                                // <1>
    id("de.itemis.mps.gradle.common") version "1.30.+"                             // <1>
}

repositories {
    maven(url = "https://artifacts.itemis.cloud/repository/maven-mps")
    mavenCentral()
}

dependencies {
    mps("com.jetbrains:mps:2025.1.2")                                              // <1>
    jbr("com.jetbrains.jdk:jbr_jcef:21.0.6-b895.109")                              // <1>
    api("io.lionweb.lionweb-mps:lionweb-mps-2025.1:0.3.0")                         // <1>
}

mpsDefaults.pathVariables.put("lionweb-mps.test-project-ExternalLib", projectDir)  // <2>

mpsBuilds {
    create<MainBuild>("main") {                                                    // <3>
        buildSolutionDescriptor = file("solutions/testProjectExternalLib.build/testProjectExternalLib.build.msd")
        buildArtifactsDirectory = file("build/artifacts/test-project-externalLib")
        buildFile = file("build.xml")
        mpsProjectDirectory = projectDir.absoluteFile                              // <4>
    }
}

tasks.register<MpsExecute>("runCommandLineTool") {
    dependsOn(tasks.resolveMpsLibraries)

    mpsHome = mpsDefaults.mpsHome.asFile.get()
    project.logger.info("mpsHome: $mpsHome")
    pluginRoots.add(mpsHome.dir("plugins"))
    projectLocation = projectDir.absoluteFile                                      // <4>
    javaLauncher = mpsDefaults.javaLauncher
    macros.putAll(mpsDefaults.pathVariables.get().map { (k, v) -> k to v.path }.toMap())
    module = "io.lionweb.mps.cmdline"
    className = "io.lionweb.mps.cmdline.CommandLineTool"
    method = "execute"
    val propArgs: String? = project.findProperty("args") as String?
    project.logger.info("propArgs: $propArgs")
    if (propArgs != null) {
        val parse = CommandLine.parse(propArgs)
        projectLocation = projectDir
        methodArguments = listOf(parse.executable) + parse.arguments.toList()
    }
}
----
<1> Adjust versions.
<2> Example how to set macros.
<3> Regular MPS build, adjust to your environment.
<4> Set MPS project directory (_in 2 places!_).
Can be omitted if MPS project directory == gradle project directory.