@startuml
hide empty members

' qualified name: "io.lionweb.serialization.validation"


abstract class ATextLocation implements ILocation

class CharacterIndexTextLocation extends ATextLocation {
  index: Integer <<optional>>
}

class CompositeLocation  implements ILocation

interface ILocation

class JsonPathLocation  implements ILocation {
  path: String <<optional>>
}

class LineColumnTextLocation extends ATextLocation {
  line: Integer <<optional>>
  column: Integer <<optional>>
}

class NodeFeatureIndexLocation extends NodeFeatureLocation {
  index: Integer <<optional>>
}

class NodeFeatureLocation extends NodeLocation {
  featureKey: String <<optional>>
}

class NodeLocation  implements ILocation {
  nodeId: String <<optional>>
}

class RangeTextLocation extends LineColumnTextLocation {
  length: Integer <<optional>>
}

CompositeLocation "1" o-- "*" ILocation: locations

































@enduml
